In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import os

In [2]:
from mpmath import *
mp.dps=300

In [3]:
df_t = pd.read_csv('income_train.csv')

In [4]:
df_v = pd.read_csv('income_test.csv',encoding="utf-8", header=1)

In [5]:
df_t_b = pd.read_csv('../input/income_train.csv')
df_v_b = pd.read_csv('../input/income_test.csv',encoding="utf-8", header=1)

In [6]:
df_t.columns = [ "Age", "Workclass", "fnlwgt", "Education", "Education_Num", "Marital_Status",
        "Occupation", "Relationship", "Race", "Sex", "Capital_Gain", "Capital_Loss",
        "Hours_per_week", "Country", "Target"]

In [7]:
df_v.columns = [ "Age", "Workclass", "fnlwgt", "Education", "Education_Num", "Marital_Status",
        "Occupation", "Relationship", "Race", "Sex", "Capital_Gain", "Capital_Loss",
        "Hours_per_week", "Country", "Target"]

In [8]:
df_v.head()

   Age   Workclass  fnlwgt   ...    Hours_per_week         Country   Target
0   38     Private   89814   ...                50   United-States   <=50K.
1   28   Local-gov  336951   ...                40   United-States    >50K.
2   44     Private  160323   ...                40   United-States    >50K.
3   18           ?  103497   ...                30   United-States   <=50K.
4   34     Private  198693   ...                30   United-States   <=50K.

[5 rows x 15 columns]

In [9]:
df_t=df_t.drop(['fnlwgt', 'Education',"Relationship", "Capital_Gain", "Capital_Loss"], axis=1)

In [10]:
df_v=df_v.drop(['fnlwgt', 'Education',"Relationship", "Capital_Gain", "Capital_Loss"], axis=1)

In [11]:
df_t['Workclass'] = df_t['Workclass'].str.replace('Self-emp-not-inc', 'Self_Employed')
df_t['Workclass'] = df_t['Workclass'].str.replace('Self-emp-inc', 'Self_Employed')
df_t['Workclass'] = df_t['Workclass'].str.replace('Local-gov', 'govt')
df_t['Workclass'] = df_t['Workclass'].str.replace('State-gov', 'govt')
df_t['Workclass'] = df_t['Workclass'].str.replace('Federal-gov', 'govt')
df_t['Workclass'] = df_t['Workclass'].str.replace('Without-pay', 'without_earning')
df_t['Workclass'] = df_t['Workclass'].str.replace('Never-worked', 'without_earning')
df_t['Workclass'] = df_t['Workclass'].str.replace('\?', 'W_Not_Specified')

In [12]:
df_v['Workclass'] = df_v['Workclass'].str.replace('Self-emp-not-inc', 'Self_Employed')
df_v['Workclass'] = df_v['Workclass'].str.replace('Self-emp-inc', 'Self_Employed')
df_v['Workclass'] = df_v['Workclass'].str.replace('Local-gov', 'govt')
df_v['Workclass'] = df_v['Workclass'].str.replace('State-gov', 'govt')
df_v['Workclass'] = df_v['Workclass'].str.replace('Federal-gov', 'govt')
df_v['Workclass'] = df_v['Workclass'].str.replace('Without-pay', 'without_earning')
df_v['Workclass'] = df_v['Workclass'].str.replace('Never-worked', 'without_earning')
df_v['Workclass'] = df_v['Workclass'].str.replace('\?', 'W_Not_Specified')

In [13]:
df_t['Country'] = df_t['Country'].str.replace('Outlying-US\(Guam-USVI-etc\)', 'Guam')
df_t['Country'] = df_t['Country'].str.replace('\?', 'C_Not_Specified')
df_t['Country'] = df_t['Country'].str.replace('Germany', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Italy', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Poland', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Scotland', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Hungary', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Yugoslavia', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Holand-Netherlands', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Ireland', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Greece', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Portugal', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('France', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('England', 'Europe')
df_t['Country'] = df_t['Country'].str.replace('Laos', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Thailand', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Cambodia', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Hong', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Iran', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Taiwan', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Japan', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Vietnam', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('China', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('India', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Philippines', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('South', 'Asia')
df_t['Country'] = df_t['Country'].str.replace('Columbia', 'South_America')
df_t['Country'] = df_t['Country'].str.replace('Peru', 'South_America')
df_t['Country'] = df_t['Country'].str.replace('Ecuador', 'South_America')
df_t['Country'] = df_t['Country'].str.replace('United-States', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Mexico', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Puerto-Rico', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Canada', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Cuba', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Jamaica', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Trinadad&Tobago', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Honduras', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Nicaragua', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Dominican-Republic', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Guam', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Haiti', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Dominican-Republic', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('El-Salvador', 'North_America')
df_t['Country'] = df_t['Country'].str.replace('Guatemala', 'North_America')

In [14]:
df_v['Country'] = df_v['Country'].str.replace('Outlying-US\(Guam-USVI-etc\)', 'Guam')
df_v['Country'] = df_v['Country'].str.replace('\?', 'C_Not_Specified')
df_v['Country'] = df_v['Country'].str.replace('Germany', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Italy', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Poland', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Scotland', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Hungary', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Yugoslavia', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Holand-Netherlands', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Ireland', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Greece', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Portugal', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('France', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('England', 'Europe')
df_v['Country'] = df_v['Country'].str.replace('Laos', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Thailand', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Cambodia', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Hong', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Iran', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Taiwan', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Japan', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Vietnam', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('China', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('India', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Philippines', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('South', 'Asia')
df_v['Country'] = df_v['Country'].str.replace('Columbia', 'South_America')
df_v['Country'] = df_v['Country'].str.replace('Peru', 'South_America')
df_v['Country'] = df_v['Country'].str.replace('Ecuador', 'South_America')
df_v['Country'] = df_v['Country'].str.replace('United-States', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Mexico', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Puerto-Rico', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Canada', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Cuba', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Jamaica', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Trinadad&Tobago', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Honduras', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Nicaragua', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Dominican-Republic', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Guam', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Haiti', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Dominican-Republic', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('El-Salvador', 'North_America')
df_v['Country'] = df_v['Country'].str.replace('Guatemala', 'North_America')

In [15]:
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Never-married', 'Single')
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Divorced', 'Single')
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Separated', 'Single')
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Widowed', 'Single')
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Married-spouse-absent', 'N_Single')
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Married-AF-spouse', 'N_Single')
df_t['Marital_Status'] = df_t['Marital_Status'].str.replace('Married-civ-spouse', 'N_Single')

In [16]:
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Never-married', 'Single')
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Divorced', 'Single')
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Separated', 'Single')
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Widowed', 'Single')
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Married-spouse-absent', 'N_Single')
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Married-AF-spouse', 'N_Single')
df_v['Marital_Status'] = df_v['Marital_Status'].str.replace('Married-civ-spouse', 'N_Single')

In [17]:
df_t['Race'] = df_t['Race'].str.replace('\?', 'R_Not_Specified')
df_t['Sex'] = df_t['Sex'].str.replace('\?', 'S_Not_Specified')

df_v['Race'] = df_v['Race'].str.replace('\?', 'R_Not_Specified')
df_v['Sex'] = df_v['Sex'].str.replace('\?', 'S_Not_Specified')

In [18]:
df_t['Occupation'] = df_t['Occupation'].str.replace('\?', 'O_Not_Specified')
df_v['Occupation'] = df_v['Occupation'].str.replace('\?', 'O_Not_Specified')

In [19]:
df_t.head()

   Age       Workclass   ...           Country  Target
0   50   Self_Employed   ...     North_America   <=50K
1   38         Private   ...     North_America   <=50K
2   53         Private   ...     North_America   <=50K
3   28         Private   ...     North_America   <=50K
4   37         Private   ...     North_America   <=50K

[5 rows x 10 columns]

In [20]:
one_hot_t_Workclass = pd.get_dummies(df_t['Workclass'])
df_t = df_t.drop('Workclass', axis=1)
df_t = df_t.join(one_hot_t_Workclass)

one_hot_t_Marital_Status = pd.get_dummies(df_t['Marital_Status'])
df_t = df_t.drop('Marital_Status', axis=1)
df_t = df_t.join(one_hot_t_Marital_Status)

one_hot_t_Occupation = pd.get_dummies(df_t['Occupation'])
df_t = df_t.drop('Occupation', axis=1)
df_t = df_t.join(one_hot_t_Occupation)

one_hot_t_Race = pd.get_dummies(df_t['Race'])
df_t = df_t.drop('Race', axis=1)
df_t = df_t.join(one_hot_t_Race)

one_hot_t_Sex = pd.get_dummies(df_t['Sex'])
df_t = df_t.drop('Sex', axis=1)
df_t = df_t.join(one_hot_t_Sex)

one_hot_t_Country = pd.get_dummies(df_t['Country'])
df_t = df_t.drop('Country', axis=1)
df_t = df_t.join(one_hot_t_Country)

lb_t_target = LabelEncoder()
df_t["Target"] = lb_t_target.fit_transform(df_t["Target"])

In [21]:
df_t_b.tail()

       39      State-gov   77516   ...    40   United-States   <=50K
32555  27        Private  257302   ...    38   United-States   <=50K
32556  40        Private  154374   ...    40   United-States    >50K
32557  58        Private  151910   ...    40   United-States   <=50K
32558  22        Private  201490   ...    20   United-States   <=50K
32559  52   Self-emp-inc  287927   ...    40   United-States    >50K

[5 rows x 15 columns]

In [22]:
df_t.tail()

       Age  Education_Num       ...         North_America   South_America
32555   27             12       ...                     1               0
32556   40              9       ...                     1               0
32557   58              9       ...                     1               0
32558   22              9       ...                     1               0
32559   52              9       ...                     1               0

[5 rows x 38 columns]

In [23]:
one_hot_v_Workclass = pd.get_dummies(df_v['Workclass'])
df_v = df_v.drop('Workclass', axis=1)
df_v = df_v.join(one_hot_v_Workclass)

one_hot_v_Marital_Status = pd.get_dummies(df_v['Marital_Status'])
df_v = df_v.drop('Marital_Status', axis=1)
df_v = df_v.join(one_hot_v_Marital_Status)

one_hot_v_Occupation = pd.get_dummies(df_v['Occupation'])
df_v = df_v.drop('Occupation', axis=1)
df_v = df_v.join(one_hot_v_Occupation)

one_hot_v_Race = pd.get_dummies(df_v['Race'])
df_v = df_v.drop('Race', axis=1)
df_v = df_v.join(one_hot_v_Race)

one_hot_v_Sex = pd.get_dummies(df_v['Sex'])
df_v = df_v.drop('Sex', axis=1)
df_v = df_v.join(one_hot_v_Sex)

one_hot_v_Country = pd.get_dummies(df_v['Country'])
df_v = df_v.drop('Country', axis=1)
df_v = df_v.join(one_hot_v_Country)

lb_v_target = LabelEncoder()
df_v["Target"] = lb_v_target.fit_transform(df_v["Target"])

In [24]:
df_v_b.tail()

       25        Private   226802   ...     40   United-States   <=50K.
16275  39        Private   215419   ...     36   United-States   <=50K.
16276  64              ?   321403   ...     40   United-States   <=50K.
16277  38        Private   374983   ...     50   United-States   <=50K.
16278  44        Private    83891   ...     40   United-States   <=50K.
16279  35   Self-emp-inc   182148   ...     60   United-States    >50K.

[5 rows x 15 columns]

In [25]:
df_t.head()

   Age  Education_Num       ...         North_America   South_America
0   50             13       ...                     1               0
1   38              9       ...                     1               0
2   53              7       ...                     1               0
3   28             13       ...                     1               0
4   37             14       ...                     1               0

[5 rows x 38 columns]

In [26]:
data_train_array = df_t.values

In [27]:
data_validation_array = df_v.values

In [28]:
df_t.shape[0]

32560

In [29]:
b = np.ones((df_t.shape[0],1))

In [30]:
data_train_array = np.column_stack([b, data_train_array])

In [31]:
y = data_train_array[:,4]

In [32]:
data_train_array = np.delete(data_train_array, [4], axis=1)

In [33]:
data_train_array.shape[1]

38

In [34]:
theta = np.ones(data_train_array.shape[1])

In [35]:
thetaTemp = theta

In [36]:
b_v = np.ones((df_v.shape[0],1))

In [37]:
data_validation_array = np.column_stack([b_v, data_validation_array])

In [38]:
y_v = data_validation_array[:,4]

In [39]:
data_validation_array = np.delete(data_validation_array, [4], axis=1)

In [40]:
iteration = 30
alpha = 0.01

In [42]:
max_val_acc = 0
for abc in range(iteration):
    for j in range(data_train_array.shape[1]):
        temp=0
        for i in range(data_train_array.shape[0]):
            thetax = np.dot(theta, data_train_array[i])
            hx = 1/(1+exp(-thetax))
            temp = temp + (alpha*((hx-y[i])*data_train_array[i][j]))
            #print(temp)
        
        thetaTemp[j] = theta[j] - temp
        temp = 0
    
    correct = 0;
    incorrect = 0;
    correct_v = 0;
    incorrect_v = 0;
    
    for k in range(data_train_array.shape[0]):
        thetax = np.dot(theta, data_train_array[k])
        hx = 1/(1+exp(-thetax))
        if(hx<0.5):
            x = 0
        else:
            x = 1
        if(y[k]==x):
            correct = correct+1
        else:
            incorrect = incorrect +1
    for l in range(data_validation_array.shape[0]):
        thetax = np.dot(theta, data_validation_array[l])
        hx = 1/(1+exp(-thetax))
        if(hx<0.5):
            x = 0
        else:
            x = 1
        if(y_v[l]==x):
            correct_v = correct_v+1
        else:
            incorrect_v = incorrect_v +1
    
    val_acc = (correct_v/(correct_v+incorrect_v))*100
    if(val_acc>max_val_acc):
        max_val_acc = val_acc
        best_theta = theta
    print("After Iteration", abc, "\n")
    theta = thetaTemp
    print(theta, "\n")
    print("Train Accuracy: ",((correct/(correct+incorrect))*100), "\n")
    print("Validation Accuracy: ",val_acc, "\n")

After Iteration 0

[-1.77370000e+02  6.34511000e+03 -1.73375388e+03 -6.74199000e+03
  3.79309663e+01  1.32100000e+01 -7.29000000e+00  1.15700000e+01
  8.40000000e-01  7.87400000e+01 -2.54800152e+01 -1.76000000e+00
  1.01000000e+00  7.98000000e+00  2.90100000e+01  1.70000000e-01
 -2.20000000e-01  2.50000000e-01 -7.32000000e+00 -9.07000000e+00
  4.00000000e-02  2.56900000e+01  3.34000000e+00  1.04600000e+01
  3.96000000e+00  2.71000000e+00  7.50000000e-01  3.42000000e+00
 -2.04000000e+00  9.60000000e-01  5.31600000e+01 -1.63499990e+01
  6.96000000e+01  3.12000000e+00  2.26000000e+00  2.09000000e+00
  4.80800000e+01  7.30000000e-01]

Train Accuracy:  61.28378378378378

Validation Accuracy:  61.28378378378378

After Iteration 1

[-1.94912854e+02  4.86225926e+03 -1.19689388e+03 -4.32856008e+03
 -6.03896637e+00  8.47000000e+00 -1.59100000e+01  6.10000000e-01
  7.20000000e-01  6.65400105e+01 -8.16400152e+01 -1.48300000e+01
  1.00000000e+00 -7.90000000e-01  3.04299525e+01 -2.73000000e+00
 -4.04000000e+00 -6.25000000e+00 -1.59600000e+01 -2.33800000e+01
 -8.70000000e-01  2.51200000e+01  2.90000000e+00  5.66000000e+00
  2.62000000e+00 -9.80000000e-01 -2.40000000e-01  1.61000000e+00
 -1.34400000e+01  2.90000000e-01 -3.20193798e-01 -5.74100014e+01
  4.23300000e+01  2.00000000e+00  1.27000000e+00  1.02000000e+00
 -1.66100089e+01  2.90000000e-01]

Train Accuracy:  55.73710073710074

Validation Accuracy:  55.651105651105645

After Iteration 2

[-2.63169146e+02  1.27273795e+03 -3.45193885e+02 -8.38800080e+02
 -1.08426377e+02 -5.22000581e+00 -2.66900000e+01 -2.03921167e+01
  5.80000000e-01  1.39363212e+01 -1.76153114e+02 -3.61700016e+01
  9.70000000e-01 -2.06799645e+01  2.06999525e+01 -7.74000000e+00
 -1.10400035e+01 -1.76399768e+01 -2.67600000e+01 -4.54414418e+01
 -1.94000000e+00  1.38300001e+01  8.90112883e-01 -8.00847164e+00
 -1.01999882e+00 -8.80000465e+00 -2.00000000e+00 -2.88000000e+00
 -3.23792147e+01 -1.07000000e+00 -1.20414149e+02 -1.21420016e+02
 -3.97843089e+01 -1.04008814e+00 -1.48000000e+00 -1.23000000e+00
 -1.53540059e+02 -4.60000000e-01]

Train Accuracy:  45.377764127764124

Validation Accuracy:  44.717444717444714

After Iteration 3

[-4.08319068e+02 -5.01616919e+03  5.65276115e+02  2.72673992e+03
 -8.42861719e+01  4.51999419e+00 -2.76600000e+01 -9.55211674e+00
  5.30000000e-01  7.17363212e+01 -1.90336624e+02 -3.46100015e+01
  9.70000000e-01 -1.50799645e+01  3.70599519e+01 -8.65000000e+00
 -1.24500035e+01 -1.70299768e+01 -2.77499972e+01 -4.76609868e+01
 -2.11000000e+00  2.91400001e+01  2.36011288e+00 -2.74847164e+00
  9.50001178e-01 -7.60000465e+00 -2.00000000e+00 -1.07000000e+00
 -3.08692147e+01 -1.20000000e+00 -8.00221211e+01 -1.20048931e+02
  2.20398385e+00  4.79911856e-01 -6.00000000e-01 -1.90000000e-01
 -1.13600348e+02 -5.00000000e-01]

Train Accuracy:  67.58906633906633

Validation Accuracy:  67.85012285012286

After Iteration 4

[-3.65185217e+02 -2.41699919e+03 -9.92011392e+02 -2.49975402e+03
 -3.46561719e+01  1.79799942e+01 -2.57500000e+01  3.85788326e+00
  5.30000000e-01  1.39096321e+02 -1.79286624e+02 -2.95400015e+01
  9.80000000e-01 -5.78996450e+00  5.67399519e+01 -7.50000000e+00
 -1.15900035e+01 -1.45299768e+01 -2.58399972e+01 -4.62909868e+01
 -2.10000000e+00  4.77300001e+01  4.47011288e+00  7.08152836e+00
  3.78000118e+00 -4.40000465e+00 -1.64000000e+00  1.69000000e+00
 -2.69992147e+01 -9.50000000e-01 -8.85212110e+00 -1.08258931e+02
  6.88239839e+01  2.69991186e+00  8.60000000e-01  1.33000000e+00
 -4.04703479e+01 -4.20000000e-01]

Train Accuracy:  75.91830466830467

Validation Accuracy:  76.37592137592138

After Iteration 5

[-2.86775217e+02  1.05263081e+03 -1.79731392e+02  8.73735981e+02
 -2.11986172e+02 -5.13000581e+00 -4.22000000e+01 -2.62321167e+01
  3.20000000e-01  5.22863212e+01 -3.39666624e+02 -6.21600015e+01
  9.00000000e-01 -3.74899645e+01  3.57599519e+01 -1.62900000e+01
 -2.44300035e+01 -3.20499768e+01 -4.23599972e+01 -7.78709868e+01
 -3.58000000e+00  2.49200001e+01  9.01128835e-02 -1.95884716e+01
 -2.66999882e+00 -1.71700047e+01 -4.39000000e+00 -5.94000000e+00
 -5.43692147e+01 -3.41000000e+00 -2.15832121e+02 -2.04178931e+02
 -8.24460161e+01 -2.59008814e+00 -3.51000000e+00 -2.36000000e+00
 -2.73210348e+02 -1.52000000e+00]

Train Accuracy:  24.081695331695332

Validation Accuracy:  23.624078624078624

After Iteration 6

[-5.33965217e+02 -8.03991919e+03  7.30738608e+02  4.43927598e+03
 -1.89076172e+02  4.47999419e+00 -4.32800000e+01 -1.54521167e+01
  2.70000000e-01  1.09636321e+02 -3.54853456e+02 -6.08100015e+01
  9.00000000e-01 -3.20299615e+01  5.19999519e+01 -1.72500000e+01
 -2.59300035e+01 -3.15199768e+01 -4.34599972e+01 -8.02509868e+01
 -3.76000000e+00  4.00400001e+01  1.53011288e+00 -1.44984716e+01
 -7.39998822e-01 -1.60800047e+01 -4.41000000e+00 -4.16000000e+00
 -5.28992156e+01 -3.58000000e+00 -1.76762121e+02 -2.03298935e+02
 -4.11960404e+01 -1.07008814e+00 -2.64000000e+00 -1.33000000e+00
 -2.34530357e+02 -1.56000000e+00]

Train Accuracy:  67.38943488943488

Validation Accuracy:  67.72727272727272

After Iteration 7

[-4.91945236e+02 -5.47032104e+03  2.21551287e+02  2.01437470e+03
 -1.40896172e+02  1.76199942e+01 -4.16000000e+01 -2.22211674e+00
  2.70000000e-01  1.76386321e+02 -3.45373456e+02 -5.58300015e+01
  9.10000000e-01 -2.29099615e+01  7.14999519e+01 -1.64000000e+01
 -2.52200035e+01 -2.91199768e+01 -4.17799972e+01 -7.91309868e+01
 -3.75000000e+00  5.84300001e+01  3.58011288e+00 -4.86847164e+00
  2.05000118e+00 -1.30900047e+01 -4.10000000e+00 -1.43000000e+00
 -4.91803094e+01 -3.36000000e+00 -1.07512121e+02 -1.92018935e+02
  2.37356091e+01  1.13991186e+00 -1.21000000e+00  1.70000000e-01
 -1.63530357e+02 -1.49000000e+00]

Train Accuracy:  75.39004914004914

Validation Accuracy:  75.9090909090909

After Iteration 8

[-4.15755005e+02 -2.05409261e+03 -8.28525594e+02 -1.27810182e+03
 -9.12661719e+01  3.10799942e+01 -3.96900000e+01  1.11878833e+01
  2.70000000e-01  2.43746321e+02 -3.34323456e+02 -5.07600015e+01
  9.20000000e-01 -1.36199615e+01  9.11799519e+01 -1.52500000e+01
 -2.43600035e+01 -2.66199768e+01 -3.98699972e+01 -7.77609868e+01
 -3.74000000e+00  7.70200001e+01  5.69011288e+00  4.96152836e+00
  4.88000118e+00 -9.89000465e+00 -3.74000000e+00  1.33000000e+00
 -4.53103094e+01 -3.11000000e+00 -3.63421211e+01 -1.80228935e+02
  9.03556091e+01  3.35991186e+00  2.50000000e-01  1.69000000e+00
 -9.04003573e+01 -1.41000000e+00]

Train Accuracy:  75.91830466830467

Validation Accuracy:  76.37592137592138

After Iteration 9

[-3.37345005e+02  1.41553739e+03 -9.92967091e+02 -1.22223612e+03
 -1.11956458e+02  2.94396346e+01 -4.72900001e+01  5.98878769e+00
  1.50000000e-01  2.46616285e+02 -3.72405021e+02 -5.95622889e+01
  9.10000000e-01 -1.88199634e+01  9.75899557e+01 -1.76500000e+01
 -2.69200035e+01 -3.12299768e+01 -4.74899972e+01 -8.87509866e+01
 -4.61000000e+00  8.24300998e+01  5.69011288e+00  3.72152836e+00
  4.67000118e+00 -1.22707464e+01 -4.46000000e+00  6.80000005e-01
 -5.34803061e+01 -3.57000001e+00 -6.14111392e+01 -2.09008937e+02
  8.41310609e+01  3.04991676e+00 -1.69859274e-01  1.10000001e+00
 -1.23678185e+02 -1.76000000e+00]

Train Accuracy:  59.97235872235872

Validation Accuracy:  60.04299754299755

After Iteration 10

[-3.72193172e+02 -8.93773507e+02 -8.24970910e+01  2.34330388e+03
 -2.83116459e+02  8.83963456e+00 -6.03400001e+01 -2.28312123e+01
 -1.00000000e-02  1.66276285e+02 -5.25825009e+02 -9.09022889e+01
  8.40000000e-01 -4.97999634e+01  7.76299557e+01 -2.59300000e+01
 -3.94000035e+01 -4.85099768e+01 -6.05899972e+01 -1.18340987e+02
 -5.81000000e+00  6.11400998e+01  1.55011288e+00 -2.16782753e+01
 -1.52999882e+00 -2.46607464e+01 -7.09000000e+00 -6.58999999e+00
 -7.98403061e+01 -5.99000001e+00 -2.56421139e+02 -2.98438937e+02
 -6.00689388e+01 -2.00008324e+00 -4.31985927e+00 -2.27999999e+00
 -3.43598180e+02 -2.83000000e+00]

Train Accuracy:  27.27579852579853

Validation Accuracy:  26.99017199017199

After Iteration 11

[-6.05623172e+02 -9.18418397e+03  8.27082909e+02  5.89634388e+03
 -2.86926461e+02  1.53796346e+01 -6.28500001e+01 -1.53612123e+01
 -7.00000000e-02  2.11136285e+02 -5.63055009e+02 -9.35122889e+01
  8.00000000e-01 -4.87799634e+01  8.96799557e+01 -2.79000000e+01
 -4.28800035e+01 -5.04399768e+01 -6.31299972e+01 -1.23680987e+02
 -6.14000000e+00  7.22700998e+01  2.09011288e+00 -2.09282753e+01
 -5.49998822e-01 -2.52507464e+01 -7.40000000e+00 -5.94999999e+00
 -8.15103061e+01 -6.55000001e+00 -2.46881139e+02 -3.08178937e+02
 -4.26889389e+01 -1.30008324e+00 -3.99985927e+00 -1.67999999e+00
 -3.37438087e+02 -2.98000000e+00]

Train Accuracy:  60.396191646191646

Validation Accuracy:  60.7002457002457

After Iteration 12

[-5.97993509e+02 -7.56355765e+03  4.60602268e+02  3.87021377e+03
 -2.52346461e+02  2.63896346e+01 -6.29500001e+01 -3.55121231e+00
 -1.00000000e-01  2.72736285e+02 -5.67395009e+02 -9.02322889e+01
  8.00000000e-01 -4.17099634e+01  1.07459956e+02 -2.83600000e+01
 -4.34800035e+01 -4.90499768e+01 -6.32499972e+01 -1.24550987e+02
 -6.23000000e+00  8.90700998e+01  3.76011288e+00 -1.37082753e+01
  1.78000118e+00 -2.34107464e+01 -7.25000000e+00 -3.75999999e+00
 -7.90503061e+01 -6.55000001e+00 -1.94441139e+02 -3.02238937e+02
  8.60148547e+00  4.99916761e-01 -2.87985927e+00 -4.59999990e-01

 -2.84378090e+02 -2.95000000e+00]

Train Accuracy:  70.8507371007371

Validation Accuracy:  71.37592137592138

After Iteration 13

[-5.40783509e+02 -4.61071904e+03 -1.15256713e+02  1.23613007e+03
 -2.02806461e+02  3.98096346e+01 -6.10600001e+01  9.84878769e+00
 -1.00000000e-01  3.40056285e+02 -5.56465009e+02 -8.51722889e+01
  8.10000000e-01 -3.24299634e+01  1.27139956e+02 -2.72700000e+01
 -4.26200035e+01 -4.65499768e+01 -6.13599972e+01 -1.23190987e+02
 -6.22000000e+00  1.07640100e+02  5.87011288e+00 -3.88827529e+00
  4.61000118e+00 -2.02307464e+01 -6.90000000e+00 -9.99999995e-01
 -7.51803061e+01 -6.30000001e+00 -1.23421139e+02 -2.90468937e+02
  7.50814855e+01  2.71991676e+00 -1.41985927e+00  1.05000001e+00
 -2.11398090e+02 -2.87000000e+00]

Train Accuracy:  75.87223587223588

Validation Accuracy:  76.35135135135135

After Iteration 14

[-4.62543509e+02 -1.14481904e+03 -1.24693051e+03 -8.95244293e+02
 -1.53176461e+02  5.32696346e+01 -5.91500001e+01  2.32587877e+01
 -1.00000000e-01  4.07416285e+02 -5.45415009e+02 -8.01022889e+01
  8.20000000e-01 -2.31399634e+01  1.46819956e+02 -2.61200000e+01
 -4.17600035e+01 -4.40499768e+01 -5.94499972e+01 -1.21820987e+02
 -6.21000000e+00  1.26230100e+02  7.98011288e+00  5.94172471e+00
  7.44000118e+00 -1.70307464e+01 -6.54000000e+00  1.76000001e+00
 -7.13103061e+01 -6.05000001e+00 -5.22511392e+01 -2.78678937e+02
  1.41701485e+02  4.93991676e+00  4.01407261e-02  2.57000001e+00
 -1.38268090e+02 -2.79000000e+00]

Train Accuracy:  75.91830466830467

Validation Accuracy:  76.37592137592138

After Iteration 15

[-3.84133509e+02  2.32481096e+03 -3.41502090e+03 -5.61888248e+03
 -1.07246461e+02  6.50296346e+01 -5.99300001e+01  3.58987877e+01
 -1.30000000e-01  4.70126285e+02 -5.38605009e+02 -7.57322889e+01
  8.30000000e-01 -1.43299634e+01  1.65789956e+02 -2.53099999e+01
 -4.10900035e+01 -4.17099768e+01 -6.02299972e+01 -1.21590987e+02
 -6.42000000e+00  1.44010100e+02  9.91011288e+00  1.49617247e+01
  1.01200012e+01 -1.41507464e+01 -6.24000000e+00  4.32000001e+00
 -6.81203061e+01 -5.82000001e+00  1.09788609e+01 -2.70819947e+02
  2.03351485e+02  7.03991676e+00  1.36014073e+00  3.88000001e+00
 -7.35507319e+01 -2.74000000e+00]

Train Accuracy:  73.78685503685503

Validation Accuracy:  74.25061425061426

After Iteration 16

[-3.14643509e+02  5.21988096e+03 -3.16136090e+03 -4.35096266e+03
 -1.42066453e+02  6.13496344e+01 -6.81200001e+01  2.74187877e+01
 -2.50000000e-01  4.63226285e+02 -5.86902307e+02 -8.70122889e+01
  8.20000000e-01 -2.20599634e+01  1.69109956e+02 -2.80799999e+01
 -4.44499970e+01 -4.76799768e+01 -6.84299972e+01 -1.34520987e+02
 -7.33000000e+00  1.46400100e+02  9.68011288e+00  1.17717302e+01
  9.26000118e+00 -1.74907464e+01 -7.15000000e+00  3.10000001e+00
 -7.82302658e+01 -6.37000001e+00 -3.13008627e+01 -3.06290912e+02
  1.83827176e+02  6.37991676e+00  6.80140726e-01  3.01000001e+00
 -1.25820738e+02 -3.14000000e+00]

Train Accuracy:  57.60135135135135

Validation Accuracy:  57.40171990171991

After Iteration 17

[-3.69382007e+02  2.11631247e+03 -2.34850090e+03 -9.66442665e+02
 -2.40115861e+02  4.68551662e+01 -7.83100001e+01  7.54878732e+00
 -3.90000000e-01  4.08286336e+02 -6.74207737e+02 -1.06921627e+02
  7.90000000e-01 -4.33009622e+01  1.59682974e+02 -3.35999999e+01
 -5.14499970e+01 -5.96099768e+01 -7.86366759e+01 -1.54960987e+02
 -8.41000000e+00  1.37480100e+02  7.61011288e+00 -6.78270460e-01
  6.06000119e+00 -2.59907464e+01 -8.92000000e+00 -9.99999995e-01
 -9.65874819e+01 -7.73000001e+00 -1.47580722e+02 -3.65132438e+02
  1.01217443e+02  3.51987915e+00 -1.89985927e+00  8.00000010e-01
 -2.58468453e+02 -3.89000000e+00]

Train Accuracy:  46.68611793611794

Validation Accuracy:  46.541769041769044

After Iteration 18

[-5.09754274e+02 -4.13708759e+03 -1.43803090e+03  2.59909734e+03
 -2.11843917e+02  5.66251662e+01 -7.88600001e+01  1.90187873e+01
 -4.30000000e-01  4.66506336e+02 -6.83517737e+02 -1.04451627e+02
  7.90000000e-01 -3.74509023e+01  1.76702974e+02 -3.44999999e+01
 -5.25899970e+01 -5.89099768e+01 -7.92066759e+01 -1.56740985e+02
 -8.57000000e+00  1.53830100e+02  9.17011288e+00  5.35172954e+00
  8.29000119e+00 -2.47605662e+01 -8.86000000e+00  9.69955395e-01
 -9.46574819e+01 -7.84000001e+00 -1.02540674e+02 -3.61372530e+02
  1.46327059e+02  5.12987915e+00 -9.29859274e-01  1.92000001e+00
 -2.13301917e+02 -3.90000000e+00]

Train Accuracy:  69.09705159705159

Validation Accuracy:  69.51474201474201

After Iteration 19

[-4.60954118e+02 -1.41559403e+03 -3.42980089e+03 -4.20381105e+03
 -1.62213917e+02  7.00851662e+01 -7.69500001e+01  3.24287873e+01
 -4.30000000e-01  5.33866336e+02 -6.72467737e+02 -9.93816266e+01
  8.00000000e-01 -2.81609023e+01  1.96382974e+02 -3.33499999e+01
 -5.17299970e+01 -5.64099768e+01 -7.72966759e+01 -1.55370985e+02
 -8.56000000e+00  1.72420100e+02  1.12801129e+01  1.51817295e+01
  1.11200012e+01 -2.15605662e+01 -8.50000000e+00  3.72995540e+00
 -9.07874819e+01 -7.59000001e+00 -3.13706738e+01 -3.49582530e+02
  2.12947059e+02  7.34987915e+00  5.30140726e-01  3.44000001e+00
 -1.40171917e+02 -3.82000000e+00]

Train Accuracy:  75.91830466830467

Validation Accuracy:  76.37592137592138

After Iteration 20

[-3.82544118e+02  2.05403597e+03 -2.61201089e+03 -8.09141045e+02
 -2.65520806e+02  5.42751645e+01 -8.71600001e+01  1.17718200e+01
 -5.70000000e-01  4.74076337e+02 -7.62508428e+02 -1.19781635e+02
  7.70000000e-01 -5.08209484e+01  1.85762974e+02 -3.92900000e+01
 -5.90999970e+01 -6.90099766e+01 -8.75366759e+01 -1.76200985e+02
 -9.67000000e+00  1.63000156e+02  8.81011288e+00  1.90172954e+00
  7.77000119e+00 -3.06497320e+01 -1.03800000e+01 -5.20044605e-01
 -1.09737482e+02 -9.03000001e+00 -1.54213169e+02 -4.09612577e+02
  1.24015970e+02  4.37987915e+00 -2.23985927e+00  1.11000425e+00
 -2.79943048e+02 -4.59000000e+00]

Train Accuracy:  45.70945945945946

Validation Accuracy:  45.68796068796069

After Iteration 21

[-5.30434103e+02 -4.46139660e+03 -1.70154089e+03  2.75639895e+03
 -2.33340806e+02  6.44950728e+01 -8.73200001e+01  2.35118200e+01
 -6.00000000e-01  5.33456376e+02 -7.67978424e+02 -1.16611635e+02
  7.70000000e-01 -4.43998532e+01  2.03272974e+02 -4.00600000e+01
 -5.99099970e+01 -6.79399766e+01 -8.77166759e+01 -1.77460985e+02
 -9.80000000e+00  1.79760156e+02  1.04501129e+01  8.72172954e+00
  1.00300012e+01 -2.92597320e+01 -1.02900000e+01  1.57995540e+00
 -1.07367482e+02 -9.11000001e+00 -1.04803168e+02 -4.04052577e+02
  1.72285970e+02  6.08987914e+00 -1.16985927e+00  2.27000425e+00
 -2.30094477e+02 -4.57000000e+00]

Train Accuracy:  70.31633906633907

Validation Accuracy:  70.80466830466831

After Iteration 22

[-4.76664103e+02 -1.61915677e+03 -3.54963746e+03 -3.45655305e+03
 -1.83710806e+02  7.79550728e+01 -8.54100001e+01  3.69218200e+01
 -6.00000000e-01  6.00816376e+02 -7.56928424e+02 -1.11541635e+02
  7.80000000e-01 -3.51098532e+01  2.22952974e+02 -3.89100000e+01
 -5.90499970e+01 -6.54399766e+01 -8.58066759e+01 -1.76090985e+02
 -9.79000000e+00  1.98350156e+02  1.25601129e+01  1.85517295e+01
  1.28600012e+01 -2.60597320e+01 -9.93000000e+00  4.33995540e+00
 -1.03497482e+02 -8.86000001e+00 -3.36331677e+01 -3.92262577e+02
  2.38905970e+02  8.30987914e+00  2.90140726e-01  3.79000425e+00
 -1.56964477e+02 -4.49000000e+00]

Train Accuracy:  75.91830466830467

Validation Accuracy:  76.37592137592138

After Iteration 23

[-3.98254103e+02  1.85047323e+03 -2.73468746e+03 -8.17030536e+01
 -3.60710766e+02  5.48550728e+01 -1.01800000e+02  6.87181999e+00
 -8.10000000e-01  5.14016376e+02 -9.16798427e+02 -1.44011635e+02
  7.00000000e-01 -6.67998532e+01  2.02072974e+02 -4.76800000e+01
 -7.18799970e+01 -8.29599766e+01 -1.02266669e+02 -2.07630985e+02
 -1.12700000e+01  1.75710156e+02  8.18011288e+00 -8.00827046e+00
  6.41000120e+00 -3.88197320e+01 -1.26700000e+01 -3.24004566e+00
 -1.30837482e+02 -1.13200000e+01 -2.40013156e+02 -4.87662577e+02
  8.78759709e+01  3.03987914e+00 -4.06985927e+00  1.10004254e-01
 -3.88924286e+02 -5.57000000e+00]

Train Accuracy:  24.37960687960688

Validation Accuracy:  23.906633906633907

After Iteration 24

[-6.44393740e+02 -7.21377945e+03 -1.82421746e+03  3.48383695e+03
 -3.15490766e+02  6.73250728e+01 -1.00480000e+02  1.97518200e+01
 -8.10000000e-01  5.79166376e+02 -9.10068427e+02 -1.39241635e+02
  7.10000000e-01 -5.82398532e+01  2.21192974e+02 -4.72800000e+01
 -7.14599970e+01 -8.06899766e+01 -1.00946669e+02 -2.06950985e+02
 -1.12900000e+01  1.93710156e+02  1.01201129e+01  1.13172954e+00
  9.08000120e+00 -3.62297320e+01 -1.23800000e+01 -5.90045658e-01
 -1.27367482e+02 -1.11200000e+01 -1.74753156e+02 -4.77192577e+02
  1.49275971e+02  5.20987914e+00 -2.70985927e+00  1.54000425e+00

 -3.22094253e+02 -5.50000000e+00]

Train Accuracy:  74.45945945945947

Validation Accuracy:  75.08599508599508

After Iteration 25

[-5.72553740e+02 -3.90930945e+03 -2.02999766e+03  1.95443706e+03
 -2.68850766e+02  8.00350728e+01 -9.89100001e+01  3.28518200e+01
 -8.10000000e-01  6.44866376e+02 -9.01748427e+02 -1.34331635e+02
  7.20000000e-01 -4.94598532e+01  2.40552974e+02 -4.67700000e+01
 -7.09099970e+01 -7.83699766e+01 -9.93766691e+01 -2.06000985e+02
 -1.12900000e+01  2.11990156e+02  1.21201129e+01  1.05217295e+01
  1.18100012e+01 -3.35697320e+01 -1.20700000e+01  2.10995434e+00
 -1.23757482e+02 -1.09200000e+01 -1.07553156e+02 -4.66182577e+02
  2.12285971e+02  7.39987914e+00 -1.30985927e+00  3.00000425e+00
 -2.53194253e+02 -5.43000000e+00]

Train Accuracy:  74.95700245700246

Validation Accuracy:  75.52211302211302

After Iteration 26

[-4.98533740e+02 -5.52659452e+02 -4.15672796e+03 -5.72848793e+03
 -2.19220766e+02  9.34950728e+01 -9.70000001e+01  4.62618200e+01
 -8.10000000e-01  7.12226376e+02 -8.90698427e+02 -1.29261635e+02
  7.30000000e-01 -4.01698532e+01  2.60232974e+02 -4.56200000e+01
 -7.00499970e+01 -7.58699766e+01 -9.74666691e+01 -2.04630985e+02
 -1.12800000e+01  2.30580156e+02  1.42301129e+01  2.03517295e+01
  1.46400012e+01 -3.03697320e+01 -1.17100000e+01  4.86995434e+00
 -1.19887482e+02 -1.06700000e+01 -3.63831556e+01 -4.54392577e+02
  2.78905971e+02  9.61987914e+00  1.50140726e-01  4.52000425e+00
 -1.80064253e+02 -5.35000000e+00]

Train Accuracy:  75.91830466830467

Validation Accuracy:  76.37592137592138

After Iteration 27

[-4.20123740e+02  2.91697055e+03 -3.35380796e+03 -2.36137181e+03
 -2.29120770e+02  9.35850244e+01 -1.03960000e+02  4.47518186e+01
 -9.30000000e-01  7.22931430e+02 -9.19798476e+02 -1.35641635e+02
  7.30000000e-01 -4.37698531e+01  2.69120149e+02 -4.76600000e+01
 -7.20399957e+01 -7.98093204e+01 -1.04446669e+02 -2.14220985e+02
 -1.20900000e+01  2.39110156e+02  1.45901129e+01  2.09817295e+01
  1.51100012e+01 -3.22997320e+01 -1.22800000e+01  4.94995434e+00
 -1.26207482e+02 -1.10600000e+01 -4.75653082e+01 -4.76872577e+02
  2.83068887e+02  9.85987914e+00  1.00140726e-01  4.15000425e+00
 -1.97921713e+02 -5.67000000e+00]

Train Accuracy:  61.71375921375921

Validation Accuracy:  61.51719901719902

After Iteration 28

[-4.38423703e+02  1.26452279e+03 -2.51593816e+03  1.05461819e+03
 -4.06420770e+02  7.04750244e+01 -1.20400000e+02  1.46618186e+01
 -1.14000000e+00  6.36121430e+02 -1.08012848e+03 -1.68251635e+02
  6.50000000e-01 -7.54698531e+01  2.48150149e+02 -5.64500000e+01
 -8.48799957e+01 -9.73293204e+01 -1.20956669e+02 -2.45780985e+02
 -1.35700000e+01  2.16310156e+02  1.02101129e+01 -5.68827046e+00
  8.66000120e+00 -4.50697320e+01 -1.50300000e+01 -2.68004566e+00
 -1.53577482e+02 -1.35200000e+01 -2.54485308e+02 -5.72712577e+02
  1.31818887e+02  4.56987914e+00 -4.26985927e+00  4.70004254e-01
 -4.30551713e+02 -6.77000000e+00]

Train Accuracy:  24.118550368550366

Validation Accuracy:  23.667076167076168

After Iteration 29

[-6.85493703e+02 -7.82549721e+03 -1.60546816e+03  4.62015819e+03
 -3.77330768e+02  8.05348564e+01 -1.20930000e+02  2.61718186e+01
 -1.18000000e+00  6.95081430e+02 -1.08902833e+03 -1.65691742e+02
  6.50000000e-01 -6.94498531e+01  2.65340149e+02 -5.72900000e+01
 -8.59699957e+01 -9.65293180e+01 -1.21506669e+02 -2.47460985e+02
 -1.37200000e+01  2.32680156e+02  1.17801129e+01  5.81212753e-01
  1.09000012e+01 -4.37197320e+01 -1.49600000e+01 -6.70045658e-01
 -1.51567482e+02 -1.36300000e+01 -2.08421427e+02 -5.68712577e+02
  1.77848887e+02  6.21987914e+00 -3.26985927e+00  1.60000425e+00
 -3.84291713e+02 -6.78000000e+00]

Train Accuracy:  69.2936117936118

Validation Accuracy:  69.73587223587224

In [44]:
print("Max Validation Accuracy: ",max_val_acc, "\n")
print("Best Theta: ",best_theta, "\n")

Max Validation Accuracy:  76.37592137592138

Best Theta:  [-6.85493703e+02 -7.82549721e+03 -1.60546816e+03  4.62015819e+03
 -3.77330768e+02  8.05348564e+01 -1.20930000e+02  2.61718186e+01
 -1.18000000e+00  6.95081430e+02 -1.08902833e+03 -1.65691742e+02
  6.50000000e-01 -6.94498531e+01  2.65340149e+02 -5.72900000e+01
 -8.59699957e+01 -9.65293180e+01 -1.21506669e+02 -2.47460985e+02
 -1.37200000e+01  2.32680156e+02  1.17801129e+01  5.81212753e-01
  1.09000012e+01 -4.37197320e+01 -1.49600000e+01 -6.70045658e-01
 -1.51567482e+02 -1.36300000e+01 -2.08421427e+02 -5.68712577e+02
  1.77848887e+02  6.21987914e+00 -3.26985927e+00  1.60000425e+00
 -3.84291713e+02 -6.78000000e+00]